name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Docker image
        run: |
          docker build -t research-bot .
      - name: Run ResearchAgent (in background)
        run: |
          docker run -d -p 5000:5000 --name research-bot \
            -e OPENAI_API_KEY=dummy \
            -e BASIC_AUTH_USERNAME=admin \
            -e BASIC_AUTH_PASSWORD=admin \
            -e SECRET_KEY=testkey \
            research-bot
      - name: Wait for service to be healthy
        run: |
          sleep 10 # Or use a curl health check to wait for API to be ready
      - name: Perform a research action (trigger file creation)
        run: |
          curl -X POST http://localhost:5000/api/research -H "Content-Type: application/json" -d '{"query": "test research"}'
      - name: Run tests
        run: |
          pip install pytest
          pytest
